import { NextRequest, NextResponse } from 'next/server';

/**
 * Poll for the latest n8n execution result
 * This API checks n8n executions and returns the actual video data when ready
 */
export async function GET(request: NextRequest) {
  try {
    const n8nBaseUrl = process.env.N8N_BASE_URL || 'http://localhost:5678';
    
    // First try to get executions without authentication (might work for some n8n setups)
    let executionsResponse;
    
    try {
      executionsResponse = await fetch(`${n8nBaseUrl}/api/v1/executions?limit=5`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
      // Skip SSL verification for self-signed certificates in development
      ...(process.env.NODE_ENV === 'development' && n8nBaseUrl.startsWith('https://localhost') && {
        // @ts-ignore - Node.js specific option
        agent: new (require('https').Agent)({
          rejectUnauthorized: false
        })
      })
      });
    } catch (apiError) {
      // If API fails, try alternative method - check n8n webhook directly
      console.log('n8n API not accessible, trying alternative method...');
      
      return NextResponse.json({
        status: 'api_unavailable',
        message: 'n8n API not accessible. Please check n8n executions manually at http://localhost:5678',
        note: 'Go to n8n > Executions tab to see the latest execution results',
        manualCheckUrl: 'http://localhost:5678'
      });
    }

    if (!executionsResponse.ok) {
      return NextResponse.json({
        status: 'api_error',
        message: `n8n API returned ${executionsResponse.status}. Check n8n authentication settings.`,
        note: 'Go to n8n > Executions tab to see the latest execution results',
        manualCheckUrl: 'http://localhost:5678'
      });
    }

    const executions = await executionsResponse.json();
    const latestExecution = executions.data?.[0];

    if (!latestExecution) {
      return NextResponse.json({
        status: 'no_executions',
        message: 'No executions found'
      });
    }

    // Check if execution is finished
    if (!latestExecution.finished) {
      return NextResponse.json({
        status: 'processing',
        message: 'Execution still in progress',
        executionId: latestExecution.id,
        startedAt: latestExecution.startedAt
      });
    }

    // Get detailed execution data
    const executionDetailResponse = await fetch(`${n8nBaseUrl}/api/v1/executions/${latestExecution.id}`, {
      method: 'GET',
      headers: {
        'Content-Type': 'application/json',
      },
      // Skip SSL verification for self-signed certificates in development
      ...(process.env.NODE_ENV === 'development' && n8nBaseUrl.startsWith('https://localhost') && {
        // @ts-ignore - Node.js specific option
        agent: new (require('https').Agent)({
          rejectUnauthorized: false
        })
      })
    });

    if (!executionDetailResponse.ok) {
      return NextResponse.json(
        { error: 'Failed to get execution details', status: executionDetailResponse.status },
        { status: executionDetailResponse.status }
      );
    }

    const executionDetail = await executionDetailResponse.json();
    
    // Extract video data from Convert to File node
    const runData = executionDetail.data?.resultData?.runData;
    if (runData && runData['Convert to File']) {
      const convertToFileData = runData['Convert to File'][0]?.data?.main?.[0];
      
      if (convertToFileData?.binary) {
        // Return binary data
        return NextResponse.json({
          status: 'completed',
          type: 'video',
          data: convertToFileData.binary,
          metadata: {
            description: 'Video generated by VEO3',
            executionId: latestExecution.id,
            finishedAt: latestExecution.stoppedAt
          }
        });
      }
      
      if (convertToFileData?.json) {
        // Return JSON data (might contain video URL)
        return NextResponse.json({
          status: 'completed',
          type: 'video',
          data: convertToFileData.json,
          metadata: {
            description: 'Video generated by VEO3',
            executionId: latestExecution.id,
            finishedAt: latestExecution.stoppedAt
          }
        });
      }
    }

    // Return execution details for debugging
    return NextResponse.json({
      status: 'completed_no_video',
      message: 'Execution completed but no video data found',
      executionId: latestExecution.id,
      nodeNames: Object.keys(runData || {}),
      executionDetail: executionDetail.data?.resultData?.runData
    });

  } catch (error) {
    console.error('Failed to poll execution:', error);
    return NextResponse.json(
      { 
        error: 'Failed to poll execution',
        message: error instanceof Error ? error.message : 'Unknown error'
      },
      { status: 500 }
    );
  }
}